[package]
name = "add"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
async-std = { version = "1.13.2", features = ["attributes"] }
clap = { version = "4.5.59", features = ["derive"] }
wasmtime = "41.0.3"
wasmtime-wasi = "41.0.3"
